# Generated by Django 3.1 on 2020-09-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(max_length=900)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_stay', models.BooleanField(default=False)),
                ('no_of_guests', models.IntegerField(blank=True, null=True)),
                ('has_breakfast', models.BooleanField(blank=True, default=True, null=True)),
                ('is_relax', models.BooleanField(default=False)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('scents', models.CharField(blank=True, max_length=254, null=True)),
                ('is_eat', models.BooleanField(default=False)),
                ('protein', models.CharField(blank=True, max_length=254, null=True)),
                ('no_of_courses', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category')),
            ],
        ),
    ]
