# Generated by Django 3.1.1 on 2020-09-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200911_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_retreat',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
